name: Upload Sources to S3

on:
  push:
    branches:
      - main
    paths:
      - 'sample-sources.yaml'
  workflow_dispatch:

jobs:
  upload-sources:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
        run: |
          aws configure set aws.access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws.secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_REGION

      - name: Upload sources to S3
        run: |
          aws s3 cp sample-sources.yaml s3://${{ secrets.S3_BUCKET_NAME }}/sources.yaml
          echo "Sources uploaded successfully to S3"