apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb.yaml
  - minio.yaml
  - temporal.yaml
  - postgresql.yaml
  - backend.yaml
  - frontend.yaml
  - nginx.yaml
  - elk.yaml
